services:
  _defaults: 
    autoconfigure: true 
    autowire: true

  Teoalboo\DtoValidator\Resolver\: 
    public: true
    resource: './Resolver/'

  Teoalboo\DtoValidator\Validator\DtoPayloadValidator:
    arguments: 
      $container: '@service_container'
      $request:   '@request_stack'

  Teoalboo\DtoValidator\EventSubscriber\DtoEventsSubscriber:
    tags: ['kernel.event_subscriber']
    arguments: 
      $translator: '@translator'
      $validator:  '@validator'