services:

  Teoalboo\DtoValidator\Resolver\: 
    public: true
    resource: '../src/Resolver/*Resolver.php'

  Teoalboo\DtoValidator\Validator\DtoPayloadValidator:
    arguments: 
      $container: '@service_container'
      $request:   '@request_stack'

  Teoalboo\DtoValidator\Validator\NotExistValidator:
    arguments: 
      $em: '@doctrine.orm.entity_manager'

  Teoalboo\DtoValidator\EventSubscriber\DtoEventsSubscriber:
    arguments: 
      $translator: '@translator'
      $validator:  '@validator'
    tags: ['kernel.event_subscriber']
