services:

  Teoalboo\DtoValidator\Resolver\ResolverFactory:
    arguments: 
      $container: '@service_container'

  Teoalboo\DtoValidator\EventSubscriber\DtoEventsSubscriber:
    arguments: 
      $translator: '@translator'
      $validator:  '@validator'    
    tags: ['kernel.event_subscriber']
