services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Teoalboo\DtoValidator\Resolver\: 
    public: true
    resource: '../src/Resolver/*Resolver.php'

  Teoalboo\DtoValidator\Service\DtoValidatorService:
    arguments: 
      $container: '@service_container'
      $validator: '@validator'

  dto_validator: '@Teoalboo\DtoValidator\Service\DtoValidatorService'

  Teoalboo\DtoValidator\EventSubscriber\DtoEventsSubscriber:
    arguments: 
      $stack:      '@request_stack'
      $translator: '@translator'
      $validator:  '@dto_validator'
    tags: ['kernel.event_subscriber']

  dto_subscriber: '@Teoalboo\DtoValidator\EventSubscriber\DtoEventsSubscriber'
