services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Teoalboo\DtoValidator\Resolver\ResolverFactory:
    arguments: 
      $container: '@service_container'

  Teoalboo\DtoValidator\Validator\DtoPayloadValidator:
    arguments: 
      $factory: '@Teoalboo\DtoValidator\Resolver\ResolverFactory'
      $request: '@request_stack'

  Teoalboo\DtoValidator\EventSubscriber\DtoEventsSubscriber:
    arguments: 
      $translator: '@translator'
      $validator:  '@validator'    
    tags: ['kernel.event_subscriber']
